### ISSUE TITLE
Please enter a short (10 lines) description of why people should come to your stand. This will be added to your stand on the overview website.

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/FOSDEM#11]

**Comment by Shoalsteed** [comment]
The invisible Internet Project is now in its 21st year. It has maintained consistent roadmaps and development during this time and created a network and community that continues to provide new and innovative technology to support privacy. The time to participate in its network growth and engineering efforts is at its most exciting and challenging as it scales to meet the needs of its community and continued resistance to censorship. The need for technologies like I2P has never been greater to provide access to information and to each other in a privacy by design manner.

**Comment by diva-exchange** [comment]
Stand visitors will learn about the research and development behind DIVA.EXCHANGE. They get deep insights into the latest projects, how I2P works together with an application like DIVA and why it's non-trivial but highly challenging to create a fully distributed, privacy-only and censorship resistant application.
