### ISSUE TITLE
Project description

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/FOSDEM#2]

**Comment by Shoalsteed** [comment]
The Invisible Internet Project (I2P) is a fully encrypted private peer-to-peer network layer. I2P uses censorship-resistant transport protocols, and has recently implemented "SSU2", a modern UDP protocol designed to the highest standards of security and blocking resistance. Additionally it also uses a transport called NTCP2 that is an authenticated key agreement protocol that improves the resistance to various forms of automated identification and attacks.
The network has an application layer as well, with easy to use API's that allow developers to build and deploy privacy aware applications. 

The project has been in active development since 2002 and is a free open source, community build network.

**Comment by diva-exchange** [comment]
The free banking project DIVA.EXCHANGE is based on the I2P protocol. It is a software development and research project in loose cooperation with Swiss Universities.The project is driven by an association, which is open to everyone and loosely connects soft- and hardware developers, researchers, privacy and finance specialists. The major motivation of the project is to create a fully and truly distributed solution for everyday banking needs for everyone (like payments, savings, investments, loans). The solution is fully distributed and self-hosted, hence there is business model, token or coin or alike involved (except donations).

The software developers and researchers loosly associated to DIVA.EXCHANGE have continiously a popular I2P-SAM library and a highly energy efficient, byzantine fault tolerant, fast and generic fully distributed storage engine (aka "blockchain", divachain) in the past years.
