### ISSUE TITLE
Social media links

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/FOSDEM#6]

**Comment by Shoalsteed** [comment]
Reddit: https://www.reddit.com/r/i2p/
Mastodon: https://mastodon.social/@i2p
Twitter: https://twitter.com/GetI2P

**Comment by diva-exchange** [comment]
Twitter: https://twitter.com/GetI2P and https://twitter.com/@DigitalValueX
Mastodon: https://mastodon.social/@i2p and https://social.diva.exchange/@social
Reddit: https://www.reddit.com/r/i2p/ and https://www.reddit.com/u/DivaExchange/

I would place twitter on top, followed by the "european focussed" mastodon and reddit at the end.
