### ISSUE TITLE
Why do you want to be at FOSDEM?

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/FOSDEM#7]

**Comment by Shoalsteed** [comment]
The I2P network has grown significantly over the years, as has the network capacity for supporting new and innovative research such as DIVA EXCHANGE, as well as providing trusted structure for people who make use of its censorship resistant transports and design. We would like to share this with other developers and also learn where the network can scale to provide services and onboarding in ways that it may have not considered. We hope to get new perspectives for future roadmaps and meet other developers, researchers and designers.

**Comment by diva-exchange** [comment]
Tx, OK for DIVA.EXCHANGE.
