### ISSUE TITLE
What is the relation between the project and the primary contact?

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/FOSDEM#8]

**Comment by diva-exchange** [comment]
**Relationship between the project and the contacts:**
The two representatives have a deep knowledge of the I2P project and, respectively, the DIVA.EXCHANGE project.

**About the "cooperation" between I2P and DIVA.EXCHANGE:**
I2P and DIVA.EXCHANGE cooperate from time to time. Some real-world examples: (a) the I2P developer team develops the I2P protocol, DIVA.EXCHANGE runs and manages some parts of the I2P bootstrapping network infrastructure (known as reseed servers). (b) I2P develops its I2P user interface, DIVA.EXCHANGE is based on a daemon version, I2Pd, and develops its own user interface and applications.

In general: the "cooperation" shall be mutually beneficial, fully distributed (independent) and free of conflicts - there are many possibilities to create realiable solutions for end users.
