### ISSUE TITLE
What is the relation between the project and the secondary contact?

### ISSUE THREAD

**Issue by Shoalsteed** [Shoalsteed/FOSDEM#9]

**Comment by diva-exchange** [comment]
See https://github.com/Shoalsteed/FOSDEM/issues/8

**Comment by Shoalsteed** [comment]
DIVA and I2P share many of the same intentions and goals with their research and development efforts. With these shared goals, they are building mutual aid and capacity into foundational privacy protocol development. Additionally, together we are exploring how our communities are needs are changing. This means working together to provide different onboarding approaches to our technologies, sharing insights for building greater resilience into the  network, and future roadmaps.
